var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/pagamentos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ll8gd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~~u8im.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_1h~fr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ybk2gh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o~d1oh._.js")
R.c("server/chunks/ssr/_0anzw1i._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ehdr20._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/_0__m-8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_0wug5b8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_pagamentos_page_actions_0ino-vb.js")
R.m(539653)
module.exports=R.m(539653).exports
