var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/broadcasts/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hehc_z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0g8_tf4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_1h~fr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ybk2gh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o~d1oh._.js")
R.c("server/chunks/ssr/_0anzw1i._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ehdr20._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/_0__m-8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_0wug5b8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_broadcasts_new_page_actions_0n2a6~o.js")
R.m(573269)
module.exports=R.m(573269).exports
