var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/mailboxes/test-imap/route.js")
R.c("server/chunks/[root-of-the-server]__0qbfrqp._.js")
R.c("server/chunks/_0e9kgm-._.js")
R.c("server/chunks/[root-of-the-server]__04-r.6z._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/[root-of-the-server]__0s973fm._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_mailboxes_test-imap_route_actions_0ieb4z8.js")
R.m(472664)
module.exports=R.m(472664).exports
