// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/agenda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agenda">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/agenda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/assinaturas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assinaturas">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/assinaturas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/[id]/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/[id]/logs">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/[id]/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/email">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/flows/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/flows/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/flows/[id]/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows/[id]/runs">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/flows/[id]/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flows">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/inbox/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbox/stats">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/inbox/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pagamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pagamentos">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pagamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pedidos">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pipelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipelines">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pipelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/join/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/invitations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/invitations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/invitations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/invitations">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/members/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/members/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/members/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/transfer-ownership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/transfer-ownership">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/transfer-ownership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automations/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../src/app/api/automations/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/automations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automations/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations/cron">> = Specific
  const handler = {} as typeof import("../../src/app/api/automations/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automations/engine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations/engine">> = Specific
  const handler = {} as typeof import("../../src/app/api/automations/engine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations">> = Specific
  const handler = {} as typeof import("../../src/app/api/automations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/check-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/check-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/check-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/pending-notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/pending-notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/pending-notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/channels">> = Specific
  const handler = {} as typeof import("../../src/app/api/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-email-tables/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-email-tables">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-email-tables/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows/[id]/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/[id]/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows/[id]/runs">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/[id]/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows/cron">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flows/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flows/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/flows/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/instagram/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instagram/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/instagram/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal-conversations/[id]/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal-conversations/[id]/clear">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal-conversations/[id]/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal-conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal-conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal-conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal-messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal-messages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal-messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invitations/[token]/peek/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]/peek">> = Specific
  const handler = {} as typeof import("../../src/app/api/invitations/[token]/peek/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invitations/[token]/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]/redeem">> = Specific
  const handler = {} as typeof import("../../src/app/api/invitations/[token]/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/linkedin/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/linkedin/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/linkedin/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mailboxes/[id]/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/[id]/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/mailboxes/[id]/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mailboxes/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/mailboxes/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mailboxes/test-imap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/test-imap">> = Specific
  const handler = {} as typeof import("../../src/app/api/mailboxes/test-imap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mailboxes/test-smtp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailboxes/test-smtp">> = Specific
  const handler = {} as typeof import("../../src/app/api/mailboxes/test-smtp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messenger/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messenger/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/messenger/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pix-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pix-payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/pix-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/presence/offline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presence/offline">> = Specific
  const handler = {} as typeof import("../../src/app/api/presence/offline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sample-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sample-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/sample-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatures">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webchat/messages/[visitor_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webchat/messages/[visitor_id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/webchat/messages/[visitor_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webchat/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webchat/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/webchat/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webchat/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webchat/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/webchat/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webchat/widget/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webchat/widget">> = Specific
  const handler = {} as typeof import("../../src/app/api/webchat/widget/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/config/verify-registration/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/config/verify-registration">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/config/verify-registration/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/media/[mediaId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/media/[mediaId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/media/[mediaId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/react/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/react">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/react/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/templates/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/templates/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/templates/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/templates/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/templates/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/templates/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/join">> = Specific
  const handler = {} as typeof import("../../src/app/join/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
