// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/accounts" | "/admin/users" | "/agenda" | "/assinaturas" | "/automations" | "/automations/[id]/edit" | "/automations/[id]/logs" | "/automations/new" | "/broadcasts" | "/broadcasts/[id]" | "/broadcasts/new" | "/contacts" | "/dashboard" | "/email" | "/flows" | "/flows/[id]" | "/flows/[id]/runs" | "/forgot-password" | "/inbox" | "/inbox/stats" | "/join/[token]" | "/login" | "/pagamentos" | "/pedidos" | "/pipelines" | "/settings" | "/signup"
type AppRouteHandlerRoutes = "/api/account" | "/api/account/invitations" | "/api/account/invitations/[id]" | "/api/account/members" | "/api/account/members/[userId]" | "/api/account/transfer-ownership" | "/api/automations" | "/api/automations/[id]" | "/api/automations/[id]/duplicate" | "/api/automations/cron" | "/api/automations/engine" | "/api/calendar" | "/api/calendar/[id]" | "/api/calendar/check-reminders" | "/api/calendar/pending-notifications" | "/api/channels" | "/api/chat-log" | "/api/create-email-tables" | "/api/flows" | "/api/flows/[id]" | "/api/flows/[id]/activate" | "/api/flows/[id]/runs" | "/api/flows/cron" | "/api/flows/templates" | "/api/instagram/webhook" | "/api/internal-conversations/[id]" | "/api/internal-conversations/[id]/clear" | "/api/internal-messages/[id]" | "/api/invitations/[token]/peek" | "/api/invitations/[token]/redeem" | "/api/linkedin/webhook" | "/api/mailboxes/[id]/send" | "/api/mailboxes/[id]/sync" | "/api/mailboxes/test-imap" | "/api/mailboxes/test-smtp" | "/api/messenger/webhook" | "/api/pix-payments" | "/api/presence/offline" | "/api/sample-data" | "/api/signatures" | "/api/webchat/messages" | "/api/webchat/messages/[visitor_id]" | "/api/webchat/send" | "/api/webchat/widget" | "/api/whatsapp/broadcast" | "/api/whatsapp/config" | "/api/whatsapp/config/verify-registration" | "/api/whatsapp/media/[mediaId]" | "/api/whatsapp/react" | "/api/whatsapp/send" | "/api/whatsapp/templates/[id]" | "/api/whatsapp/templates/submit" | "/api/whatsapp/templates/sync" | "/api/whatsapp/webhook"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/join"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/accounts": {}
  "/admin/users": {}
  "/agenda": {}
  "/api/account": {}
  "/api/account/invitations": {}
  "/api/account/invitations/[id]": { "id": string; }
  "/api/account/members": {}
  "/api/account/members/[userId]": { "userId": string; }
  "/api/account/transfer-ownership": {}
  "/api/automations": {}
  "/api/automations/[id]": { "id": string; }
  "/api/automations/[id]/duplicate": { "id": string; }
  "/api/automations/cron": {}
  "/api/automations/engine": {}
  "/api/calendar": {}
  "/api/calendar/[id]": { "id": string; }
  "/api/calendar/check-reminders": {}
  "/api/calendar/pending-notifications": {}
  "/api/channels": {}
  "/api/chat-log": {}
  "/api/create-email-tables": {}
  "/api/flows": {}
  "/api/flows/[id]": { "id": string; }
  "/api/flows/[id]/activate": { "id": string; }
  "/api/flows/[id]/runs": { "id": string; }
  "/api/flows/cron": {}
  "/api/flows/templates": {}
  "/api/instagram/webhook": {}
  "/api/internal-conversations/[id]": { "id": string; }
  "/api/internal-conversations/[id]/clear": { "id": string; }
  "/api/internal-messages/[id]": { "id": string; }
  "/api/invitations/[token]/peek": { "token": string; }
  "/api/invitations/[token]/redeem": { "token": string; }
  "/api/linkedin/webhook": {}
  "/api/mailboxes/[id]/send": { "id": string; }
  "/api/mailboxes/[id]/sync": { "id": string; }
  "/api/mailboxes/test-imap": {}
  "/api/mailboxes/test-smtp": {}
  "/api/messenger/webhook": {}
  "/api/pix-payments": {}
  "/api/presence/offline": {}
  "/api/sample-data": {}
  "/api/signatures": {}
  "/api/webchat/messages": {}
  "/api/webchat/messages/[visitor_id]": { "visitor_id": string; }
  "/api/webchat/send": {}
  "/api/webchat/widget": {}
  "/api/whatsapp/broadcast": {}
  "/api/whatsapp/config": {}
  "/api/whatsapp/config/verify-registration": {}
  "/api/whatsapp/media/[mediaId]": { "mediaId": string; }
  "/api/whatsapp/react": {}
  "/api/whatsapp/send": {}
  "/api/whatsapp/templates/[id]": { "id": string; }
  "/api/whatsapp/templates/submit": {}
  "/api/whatsapp/templates/sync": {}
  "/api/whatsapp/webhook": {}
  "/assinaturas": {}
  "/automations": {}
  "/automations/[id]/edit": { "id": string; }
  "/automations/[id]/logs": { "id": string; }
  "/automations/new": {}
  "/broadcasts": {}
  "/broadcasts/[id]": { "id": string; }
  "/broadcasts/new": {}
  "/contacts": {}
  "/dashboard": {}
  "/email": {}
  "/flows": {}
  "/flows/[id]": { "id": string; }
  "/flows/[id]/runs": { "id": string; }
  "/forgot-password": {}
  "/inbox": {}
  "/inbox/stats": {}
  "/join": {}
  "/join/[token]": { "token": string; }
  "/login": {}
  "/pagamentos": {}
  "/pedidos": {}
  "/pipelines": {}
  "/settings": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/join": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
