var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/mailboxes/[id]/send/route.js")
R.c("server/chunks/[root-of-the-server]__09vjqq.._.js")
R.c("server/chunks/_0e9kgm-._.js")
R.c("server/chunks/[root-of-the-server]__09bdt6k._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/[root-of-the-server]__0xb.-p4._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/_next-internal_server_app_api_mailboxes_[id]_send_route_actions_0btgjku.js")
R.m(495805)
module.exports=R.m(495805).exports
