var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/mailboxes/[id]/sync/route.js")
R.c("server/chunks/[root-of-the-server]__04ew_55._.js")
R.c("server/chunks/_0e9kgm-._.js")
R.c("server/chunks/[root-of-the-server]__04-r.6z._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/[root-of-the-server]__0s973fm._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/node_modules_0yf77~3._.js")
R.c("server/chunks/_next-internal_server_app_api_mailboxes_[id]_sync_route_actions_0k-1iac.js")
R.m(834768)
module.exports=R.m(834768).exports
