var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/whatsapp/templates/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__03l57xu._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1253thy.js")
R.c("server/chunks/src_lib_whatsapp_meta-api_ts_0dip0p~._.js")
R.c("server/chunks/_0e9kgm-._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0hp37pu._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/_next-internal_server_app_api_whatsapp_templates_[id]_route_actions_0coprub.js")
R.m(489987)
module.exports=R.m(489987).exports
